  [firebase]
  apiKey: "AIzaSyDR2kuKWZ8_A9Mn6ME2P_S5KRd75nc2q6E",
  authDomain: "tourism-payment-sys.firebaseapp.com",
  databaseURL: "https://tourism-payment-sys-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "tourism-payment-sys",
  storageBucket: "tourism-payment-sys.firebasestorage.app",
  messagingSenderId: "1042669209748",
  appId: "1:1042669209748:web:7a53829489a83c9f794c81"